import { json, LoaderFunctionArgs } from "@remix-run/node";
import { prisma } from "~/lib/prisma/client";
import { spotifyStrategy } from "~/services/auth.server";
import {
  SpotifyCreatePlaylistResponse,
  SpotifyImageType,
} from "~/types/spotify";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const session = await spotifyStrategy.getSession(request);

  // No session, not authenticated
  if (
    !session?.accessToken ||
    !session.user ||
    new Date(session.expiresAt) <= new Date()
  ) {
    return json({ success: false }, 401);
  }

  const params = new URL(request.url).searchParams;

  const playlistName = params.get("name");
  const isPrivatePlaylist = params.get("isPrivate")?.toUpperCase() === "TRUE";
  const trackUris = params.get("tracks");

  if (!playlistName) {
    return json({ success: false }, 400);
  }

  if (!trackUris) {
    return json({ success: false }, 400);
  }

  const createPlaylistRequestUrl = `https://api.spotify.com/v1/users/${session.user.id}/playlists`;

  // Make the create playlist request
  const createPlaylistRequest = await fetch(createPlaylistRequestUrl, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${session.accessToken}`,
    },
    body: JSON.stringify({
      name: playlistName,
      description: "Created by Spotify recommendations",
      public: !isPrivatePlaylist,
    }),
  });

  // Get the response
  const createPlaylistResponse: SpotifyCreatePlaylistResponse =
    await createPlaylistRequest.json();

  // do we have an ID for the playlist?
  if (!createPlaylistResponse.id) {
    throw new Error("Failed to create playlist");
  }

  // add songs to the playlist
  const updatePlaylistRequest = await fetch(
    `https://api.spotify.com/v1/playlists/${createPlaylistResponse.id}/tracks?uris=${trackUris}`,
    {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
      },
    }
  );

  // get the response
  const res = await updatePlaylistRequest.json();

  // Get the cover image which has been generated by Spotify
  const coverReq = await fetch(
    `https://api.spotify.com/v1/playlists/${createPlaylistResponse.id}/images`,
    {
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
      },
    }
  );

  const coverRes: SpotifyImageType[] = await coverReq.json();

  // add the playlist to our db
  await prisma?.playlist.create({
    data: {
      id: createPlaylistResponse.id,
      name: playlistName,
      url: createPlaylistResponse.href,
      cover: coverRes[0]?.url || "",
      isPrivate: isPrivatePlaylist,
      creator: {
        connect: {
          id: session.user.id,
        },
      },
      tracks: {
        connect: trackUris.split(",").map((spotifyUri) => ({ spotifyUri })),
      },
    },
  });

  return json(
    {
      success: true,
      data: [{ updateResponse: res, createResponse: createPlaylistResponse }],
    },
    200
  );
};
